languageCode = 'en-us'
title = 'TLA+ Foundation'
pygmentsUseClassic = true
PygmentsCodeFences = true
enableRobotsTXT = true
noChmod = true
staticDir = ['static']

[Params]
    disableInlineCopyToClipBoard = false
    disableAssetsBusting = true
    disableLandingPageButton = false
    disableNextPrev = true
    disableSearch = true
    disableShortcutsTitle = false
    [Params.Author]
        Name = "TLA+ Foundation"
    [Params.ThemeVariant]
        identifier = 'tlaplus'

[markup]
[markup.goldmark.renderer]
    unsafe = true

[menu]
    [[menu.shortcuts]]
        pre = '<i class="fa-fw fab fa-github"></i> '
        name = 'GitHub'
        url = 'https://github.com/tlaplus/'
        weight = 10

    [[menu.shortcuts]]
        pre = '<i class="fa-fw fas fa-at"></i> '
        name = 'Mailing List'
        url = 'https://groups.google.com/g/tlaplus/'
        weight = 30

    [[menu.shortcuts]]
        pre = '<i class="fa-fw fas fa-calendar-day"></i> '
        name = 'Conferences and Events'
        url = 'https://conf.tlapl.us/home/'
        weight = 40


[module]
[[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'